import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
export const dynamic='force-dynamic';
export default async function AdminPage(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');const {data:profile}=await supabase.from('profiles').select('role,email,full_name').eq('id',user.id).single();if(profile?.role!=='admin')redirect('/admin/login');
const [{count:products},{count:customers},{count:orders},{count:pendingOrders},{count:pendingFunding},{count:approvedFunding},{count:rejectedFunding},{data:paidOrders},{data:recentOrders}]=await Promise.all([
 supabase.from('products').select('*',{count:'exact',head:true}),supabase.from('profiles').select('*',{count:'exact',head:true}).eq('role','customer'),supabase.from('orders').select('*',{count:'exact',head:true}),supabase.from('orders').select('*',{count:'exact',head:true}).eq('status','pending'),supabase.from('funding_requests').select('*',{count:'exact',head:true}).eq('status','pending'),supabase.from('funding_requests').select('*',{count:'exact',head:true}).eq('status','approved'),supabase.from('funding_requests').select('*',{count:'exact',head:true}).eq('status','rejected'),supabase.from('orders').select('total_ngn').in('status',['paid','processing','completed']),supabase.from('orders').select('id,product_name,total_ngn,status,created_at,customer:profiles!orders_customer_id_fkey(full_name,email)').order('created_at',{ascending:false}).limit(8)
]);
const revenue=(paidOrders||[]).reduce((sum,o)=>sum+Number(o.total_ngn||0),0);
return <main className="container" style={{padding:'40px 0 70px'}}><div className="nav"><div><div className="brand">Admin Dashboard</div><div className="muted">{profile.email}</div></div></div><section className="section">
<div className="stat-grid"><div className="card"><h3>Total customers</h3><div className="price">{customers??0}</div></div><div className="card"><h3>Total products</h3><div className="price">{products??0}</div></div><div className="card"><h3>Total orders</h3><div className="price">{orders??0}</div></div><div className="card"><h3>Total revenue</h3><div className="price">₦{revenue.toLocaleString()}</div></div></div>
<div className="stat-grid" style={{marginTop:16}}><div className="card"><h3>Pending orders</h3><div className="price">{pendingOrders??0}</div></div><div className="card"><h3>Pending funding</h3><div className="price">{pendingFunding??0}</div></div><div className="card"><h3>Approved funding</h3><div className="price">{approvedFunding??0}</div></div><div className="card"><h3>Rejected funding</h3><div className="price">{rejectedFunding??0}</div></div></div>
<div className="card" style={{marginTop:24}}><h2>Quick management</h2><div className="actions"><a className="btn secondary" href="/admin/customers">Customers</a><a className="btn secondary" href="/admin/funding">Funding & receipts</a><a className="btn secondary" href="/admin/orders">Orders</a><a className="btn secondary" href="/admin/products">Products</a><a className="btn secondary" href="/admin/site-contact">Site Contact</a></div></div>
<div className="card" style={{marginTop:24}}><h2>Recent orders</h2>{recentOrders?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Customer</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{recentOrders.map((o:any)=><tr key={o.id}><td>{o.product_name}</td><td>{o.customer?.full_name||o.customer?.email||'Customer'}</td><td>₦{Number(o.total_ngn).toLocaleString()}</td><td><span className="status">{o.status}</span></td><td>{new Date(o.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<p className="muted">No orders yet.</p>}</div>
</section></main>}